[application]
asset_dir = "assets"
default_platform = "web"
name = "cryonics-community-dioxus"
out_dir = "dist"

[web.app]
title = "Cryonics Community"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]

[web.resource]
style = ["/stylesheet.css"]
script = []

[web.resource.dev]
script = []
style = []
